### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by ppapapetrou76** [awaitility/awaitility#94]
Classes implementing the `AwaitilitySupport` trait are failing when using scala 2.12.x with the following message 
```
failed: java.lang.NoSuchMethodError: org.awaitility.scala.AwaitilitySupport.$init$(Lorg/awaitility
/scala/AwaitilitySupport;)V
```
The same code works fine with scala 2.11.8

**Comment by johanhaleby** [comment]
Yeah I tried to update it but I don't want Awaitility to depend on Java 8 so I had to revert. Do you know of any solution to this?

**Comment by leozilla** [comment]
Any updates? I think its ok now (in 2019) to let awaility depend on java 8

**Comment by michalmela** [comment]
One workaround is just not to use the `AwaitilitySupport` trait (and, in fact, the `awaitility-scala` as well) at all. It doesn't add all that much in fact, just some implicit conversions to bridge the *tiny* (in Scala 2.12) gap between the Scala lambdas and the `java.util.Callable`. The gap being: writing the `() =>` explicitly to differentiate a code block from lambda coercion. So to get started with using awaitility in a Scala test without the `awaitility-scala` dependency:

```
import org.awaitility
import org.awaitility.Awaitility._
import org.awaitility.core.ThrowingRunnable
import scala.concurrent.duration._

// OPTION 1: add implicit conversions
  implicit def byNameFunctionToCallableOfType[T](function: => T): Callable[T] = () => function
  implicit def byNameFunctionToCallableOfBoolean(function: => scala.Boolean): Callable[java.lang.Boolean] = () => function
  implicit def byNameFunctionToRunnable[T](function: => T): ThrowingRunnable = () => function

await atMost 5.seconds until { true == true }

// OPTION 2: ditch the conversions

await atMost 5.seconds until { () => true == true }
```

**Comment by johanhaleby** [comment]
@michalmela Thanks for the tip!

**Comment by johanhaleby** [comment]
The new version of awaitility, 4.0.0-rc1, uses Scala 2.13.0. You could try that out. I'm going to close this issue.
