### PR TITLE
Removing Duration.SAME_AS_POLL_INTERVAL.

### PR DESCRIPTION
**Pull request by greenjoe**
Duration.SAME_AS_POLL_INTERVAL has been deprecated before and using it does not work as expected anyway (the exception is thrown).

Code that starts throwing exception after migration from 1.5.0 

```
      Awaitility.await().atMost(Duration.FIVE_SECONDS)
                .pollInterval(Duration.ONE_HUNDRED_MILLISECONDS)
                .pollDelay(Duration.SAME_AS_POLL_INTERVAL)
                .until(() -> true);
```

the exception is 

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot delay polling forever
	at org.awaitility.core.ConditionFactory.generateConditionSettings(ConditionFactory.java:792)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:785)
	at MainClass.main(MainClass.java:14)
```

It seems to be better to get compilation error when migrating from an older version than to get exception during tests.

### CODE REVIEW

**Comment by johanhaleby** [comment]
Thanks for the PR. You're right, it should probably be removed by now. 

> Exception in thread "main" java.lang.IllegalArgumentException: Cannot delay polling forever
    at org.awaitility.core.ConditionFactory.generateConditionSettings(ConditionFactory.java:792)
    at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:785)
    at MainClass.main(MainClass.java:14)

This looks a bug but by accepting your PR we won't need to deal with it. Thanks again!
